// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --local > src/lib/database.types.ts
// For now, we'll use a minimal type definition

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      words: {
        Row: {
          id: string
          word: string
          created_at: string
        }
        Insert: {
          id?: string
          word: string
          created_at?: string
        }
        Update: {
          id?: string
          word?: string
          created_at?: string
        }
      }
      word_pairs: {
        Row: {
          id: string
          word_id: string
          back: string
          user_id: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          word_id: string
          back: string
          user_id: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          word_id?: string
          back?: string
          user_id?: string
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
